name: CI Run

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - recursive: false
      - name: Run Typescript Compile
        run: pnpm run typecheck
      - name: Run Biome
        run: pnpm run ci
