name: CI Run

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          run_install: true
      - name: Run Biome
        run: pnpm run ci
