name: build-win-steam-beta
on:
   push:
   workflow_dispatch:
jobs:
   run-script:
      runs-on: [self-hosted]
      steps:
         - run: |
              git checkout .
              git pull
              pnpm install
           working-directory: /home/insraq/CivIdle
         - run: |
              npm install
           working-directory: /home/insraq/CivIdle/electron
         - run: npm run release
           working-directory: /home/insraq/CivIdle
           env:
              STEAMWORKS_PATH: /home/insraq/steamworks/tools/ContentBuilder/
         - run: |
              npm install
              npm run build
              sudo systemctl restart cividle
              sudo systemctl status cividle
           working-directory: /home/insraq/CivIdle/server
         - run: |
              git add src/scripts/Version.json
              git commit -m "[skip ci] New build"
              git push
           working-directory: /home/insraq/CivIdle
