name: build-win-steam-beta
on:
   push:
   workflow_dispatch:
jobs:
   run-script:
      runs-on: [self-hosted]
      steps:
         - run: |
              git checkout .
              git submodule update --recursive --remote --init
              pnpm install
           working-directory: /home/insraq/CivIdle
         - run: |
              npm install
           working-directory: /home/insraq/CivIdle/electron
         - run: |
              npm install
              npm run build
           working-directory: /home/insraq/CivIdle/server
         - run: npm run release
           working-directory: /home/insraq/CivIdle
           env:
              STEAMWORKS_PATH: /home/insraq/steamworks/tools/ContentBuilder/
         - run: ssh ubuntu@uk.fishpondstudio.com "cd /home/ubuntu/CivIdle/ && git submodule update --recursive --remote --init && cd ./server && git checkout . && npm install && npm run build && sudo systemctl restart cividle"
         - run: |
              git add src/scripts/Version.json
              git commit -m "[skip ci] New build" || echo "There's nothing to commit"
              git push
           working-directory: /home/insraq/CivIdle
