name: build-win-steam-beta
on:
  push:
  workflow_dispatch:
jobs:
  run-script:
    runs-on: [self-hosted]
    steps:
      - run: |
          git pull
          pnpm install
        working-directory: /home/insraq/CivIdle      
      - run: npm install
        working-directory: /home/insraq/CivIdle/electron
      - run: | 
          npm install
          npm run build
          sudo service cividle restart
        working-directory: /home/insraq/CivIdle/server
      - run: npm run release
        working-directory: /home/insraq/CivIdle
        env:
          STEAMWORKS_PATH: /home/insraq/steamworks/tools/ContentBuilder/
